name: dart_math
description: A Simple Math Library for Dart
version: 0.0.9
homepage: https://github.com/Bandoh/DartMath.git
author: Bandoh <kelquans@gmail.com>

environment:
  sdk: '2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.3.0
